### GET ITEMS
GET http://localhost:3000/items HTTP/1.1

### GET SINGLE ITEM
GET http://localhost:3000/items/60daae4e5ed27116f8e19d12 HTTP/1.1

### CREATE ITEM
POST http://localhost:3000/items HTTP/1.1
Content-Type: application/json

{
    "name": "New Item",
    "qty": 100,
    "description": "This is item one"
}

### DELETE SINGLE ITEM
DELETE http://localhost:3000/items/60daae4e5ed27116f8e19d12 HTTP/1.1

### UPDATE SINGLE ITEM
PUT http://localhost:3000/items/60daafddf3b0a10518bb77ba HTTP/1.1
Content-Type: application/json

{
    "name": "Updated Item",
    "qty": 100,
    "description": "This is item one"
}